version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_pgbouncer_test
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
